package com.blt;

import com.blt.nn.LayerNorm;
import com.blt.nn.Linear;
import com.blt.tensor.Tensor;
import com.blt.transformer.GPT;
import com.blt.transformer.MultiHeadAttention;

import java.util.Arrays;

/**
 * Main entry point for the Byte Latent Transformer assignment.
 *
 * ASSIGNMENT:
 * This class is your playground. Once you have implemented the Tensor class
 * and the Layers, use this to test them.
 *
 * 1. Verify Tensor math (Matmul, Add)
 * 2. Create a simple Linear layer and pass data through it.
 * 3. Finally, instantiate your GPT model and try to overfit a simple sequence.
 */
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, Byte Latent Transformer!");

        Tensor a = new Tensor(new float[][] { { 1, 2 }, { 3, 4 } });
        Tensor b = new Tensor(new float[][] { { 5, 6 }, { 7, 8 } });
        Tensor c = a.matmul(b);
        System.out.println("Matmul Result:");
        System.out.println(Arrays.deepToString(c.getData()));

        Linear linear = new Linear(2, 3);
        Tensor linearOut = linear.forward(a);
        System.out.println("Linear output shape: " + linearOut);

        LayerNorm layerNorm = new LayerNorm(2);
        Tensor normed = layerNorm.forward(a);
        System.out.println("LayerNorm Result:");
        System.out.println(Arrays.deepToString(normed.getData()));

        MultiHeadAttention attention = new MultiHeadAttention(4, 2);
        Tensor attentionInput = new Tensor(new float[][] {
                { 0.1f, 0.2f, 0.3f, 0.4f },
                { 0.2f, 0.1f, 0.4f, 0.3f },
                { 0.3f, 0.4f, 0.1f, 0.2f }
        });
        Tensor attentionOut = attention.forward(attentionInput);
        System.out.println("Attention output shape: " + attentionOut);

        GPT gpt = new GPT(256, 16, 2, 4, 32);
        Tensor logits = gpt.forward(new Tensor(new float[][] { { 'B', 'L', 'T' } }));
        System.out.println("GPT logits shape: " + logits);
        System.out.println("Generated byte count: " + gpt.generateBytes(new byte[] { 'B', 'L', 'T' }, 4).length);
    }
}
